version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=111111
      - SPRING_DATASOURCE_SCHEMA=TOBACCO
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=TOBACCO

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111111
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./CreateDB.sql:/docker-entrypoint-initdb.d/CreateDB.sql
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  postgres-data: